#!/bin/sh

type -p gtk-update-icon-cache > /dev/null 2>&1 && usr/bin/gtk-update-icon-cache -qtf usr/share/icons/hicolor
type -p update-desktop-database > /dev/null 2>&1 && usr/bin/update-desktop-database -q usr/share/applications

groupadd -r kodi
useradd -r -m -d /var/lib/kodi -g kodi -s /usr/bin/nologin kodi
usermod -a -G kodi,audio,video,disk,input,tty,root,users,games kodi
mkdir -p /var/lib/kodi
chown -R kodi:kodi /var/lib/kodi
