#!/bin/sh

type -p gtk-update-icon-cache > /dev/null 2>&1 && usr/bin/gtk-update-icon-cache -qtf usr/share/icons/hicolor
type -p update-desktop-database > /dev/null 2>&1 && usr/bin/update-desktop-database -q usr/share/applications

groupadd -r kodi
useradd -r -m -d /var/lib/kodi -g kodi -s /usr/bin/nologin kodi
usermod -a -G kodi,audio,video,disk,input,tty,root kodi
mkdir -p /var/lib/kodi
chown -R kodi:kodi /var/lib/kodi

chmod 0666 /sys/class/graphics/fb0/mode
chmod 0666 /sys/class/graphics/fb0/blank
chmod 0666 /sys/class/graphics/fb0/free_scale
chmod 0666 /sys/class/graphics/fb0/free_scale_axis
#chmod 0666 /sys/class/graphics/fb0/request2XScale
chmod 0666 /sys/class/graphics/fb0/scale_width
chmod 0666 /sys/class/graphics/fb0/scale_height
chmod 0666 /sys/class/graphics/fb1/blank
chmod 0666 /sys/class/graphics/fb1/scale_width
chmod 0666 /sys/class/graphics/fb1/scale_height
chmod 0666 /sys/class/graphics/fb1/free_scale
chmod 0666 /sys/class/graphics/fb1/scale
chmod 0666 /sys/class/graphics/fb1/scale_axis
chmod 0666 /sys/class/display/mode
chmod 0666 /sys/class/display/axis
chmod 0666 /sys/class/amhdmitx/amhdmitx0/disp_mode
chmod 0666 /sys/class/tsync/pts_pcrscr
chmod 0666 /sys/class/tsync/enable
chmod 0666 /sys/class/video/axis
chmod 0666 /sys/class/video/zoom
chmod 0666 /sys/class/video/contrast
chmod 0666 /sys/class/video/brightness
chmod 0666 /sys/class/video/saturation
chmod 0666 /sys/class/video/blackout_policy
chmod 0666 /sys/class/video/screen_mode
chmod 0666 /sys/class/video/disable_video
chmod 0666 /sys/class/audiodsp/digital_raw
chmod 0666 /sys/class/ppmgr/ppmgr_3d_mode
chmod 0666 /sys/class/ppmgr/ppscaler
chmod 0666 /sys/class/ppmgr/ppscaler_rect
chmod 0666 /sys/class/ppmgr/disp
#chmod 0666 /sys/modules/di/parameters/bypass_all
